// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.diabblog.domain;

import org.diabblog.domain.EntryIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EntryIntegrationTest_Roo_Configurable {
    
    declare @type: EntryIntegrationTest: @Configurable;
    
}
