// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.diabblog.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.diabblog.domain.Entry;
import org.diabblog.domain.EntryDataOnDemand;
import org.diabblog.domain.EntryIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EntryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EntryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EntryIntegrationTest: @Transactional;
    
    @Autowired
    EntryDataOnDemand EntryIntegrationTest.dod;
    
    @Test
    public void EntryIntegrationTest.testCountEntrys() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        long count = Entry.countEntrys();
        Assert.assertTrue("Counter for 'Entry' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EntryIntegrationTest.testFindEntry() {
        Entry obj = dod.getRandomEntry();
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide an identifier", id);
        obj = Entry.findEntry(id);
        Assert.assertNotNull("Find method for 'Entry' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Entry' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EntryIntegrationTest.testFindAllEntrys() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        long count = Entry.countEntrys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Entry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Entry> result = Entry.findAllEntrys();
        Assert.assertNotNull("Find all method for 'Entry' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Entry' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EntryIntegrationTest.testFindEntryEntries() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        long count = Entry.countEntrys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Entry> result = Entry.findEntryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Entry' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Entry' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EntryIntegrationTest.testFlush() {
        Entry obj = dod.getRandomEntry();
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide an identifier", id);
        obj = Entry.findEntry(id);
        Assert.assertNotNull("Find method for 'Entry' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEntry(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Entry' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EntryIntegrationTest.testMergeUpdate() {
        Entry obj = dod.getRandomEntry();
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide an identifier", id);
        obj = Entry.findEntry(id);
        boolean modified =  dod.modifyEntry(obj);
        Integer currentVersion = obj.getVersion();
        Entry merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Entry' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EntryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        Entry obj = dod.getNewTransientEntry(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Entry' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Entry' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EntryIntegrationTest.testRemove() {
        Entry obj = dod.getRandomEntry();
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide an identifier", id);
        obj = Entry.findEntry(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Entry' with identifier '" + id + "'", Entry.findEntry(id));
    }
    
}
